import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import localFont from "next/font/local";
import BootstrapClient from "./Components/BootstrapClient";
import { CustomNavbar } from "./Components/CustomNavbar";
import { LeftMenubar } from "./Components/LeftMenubar";
import PrelineScript from "./Components/PrelineScript";
import { AppWrapper } from "./Context/AppContext";
import "./globals.css";


const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
  });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.variable}`}
      >
        {/* <AppRouterCacheProvider options={{ enableCssLayer: true, key: 'css' }}> */}
          {/* <ThemeProvider theme={theme}> */}
            {/* <CssBaseline /> */}
            <AppWrapper>
              <div className="min-h-screen">
                <CustomNavbar />
                <div className="flex">
                  <div>
                    <LeftMenubar />
                  </div>
                  <div className="flex justify-center items-center max-width">
                    {children}
                  </div>
                </div>
              </div>
            </AppWrapper>
          {/* </ThemeProvider> */}
        {/* </AppRouterCacheProvider> */}
        <BootstrapClient/>
      </body>
      <PrelineScript />
    </html>
  );
}
