import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import localFont from "next/font/local";
import BootstrapClient from "./Components/BootstrapClient";
import { CustomNavbar } from "./Components/CustomNavbar";
import { LeftMenubar } from "./Components/LeftMenubar";
import { AppWrapper } from "./Context/AppContext";
import "./globals.css";


const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-hidden ${geistSans.variable} ${geistMono.variable} antialiased ${roboto.variable}`}
      >
        {/* <AppRouterCacheProvider options={{ enableCssLayer: true, key: 'css' }}> */}
        {/* <ThemeProvider theme={theme}> */}
        {/* <CssBaseline /> */}
        <AppWrapper>
          <div className="min-h-screen overflow-hidden">
            <CustomNavbar />
            <div className="flex overflow-hidden">
              <div className="">
                <LeftMenubar />
              </div>
              <div className="overflow-hidden flex-1 flex">
                {children}
              </div>
            </div>
          </div>
        </AppWrapper>
        {/* </ThemeProvider> */}
        {/* </AppRouterCacheProvider> */}
        <BootstrapClient />
      </body>
    </html>
  );
}
